// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonReviewApp.Data;

#nullable disable

namespace PokReview.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240115140459_ThirdMig")]
    partial class ThirdMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokReview.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leaf"
                        });
                });

            modelBuilder.Entity("PokReview.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kanto"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Saffron City"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Millet Town"
                        });
                });

            modelBuilder.Entity("PokReview.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            FirstName = "Jack",
                            Gym = "Brocks Gym",
                            LastName = "London"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            FirstName = "Harry",
                            Gym = "Mistys Gym",
                            LastName = "Potter"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            FirstName = "Ash",
                            Gym = "Ashs Gym",
                            LastName = "Ketchum"
                        });
                });

            modelBuilder.Entity("PokReview.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1903, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pikachu"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1903, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Squirtle"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1903, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Venasuar"
                        });
                });

            modelBuilder.Entity("PokReview.Models.PokemonCategory", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("PokemonId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PokemonCategories");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            PokemonId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            PokemonId = 3,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("PokReview.Models.PokemonOwner", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("PokemonId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("PokemonOwners");
                });

            modelBuilder.Entity("PokReview.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PokemonId = 1,
                            Rating = 5,
                            ReviewerId = 1,
                            Text = "Pickahu is the best pokemon, because it is electric",
                            Title = "Pikachu"
                        },
                        new
                        {
                            Id = 2,
                            PokemonId = 1,
                            Rating = 5,
                            ReviewerId = 2,
                            Text = "Pickachu is the best a killing rocks",
                            Title = "Pikachu"
                        },
                        new
                        {
                            Id = 3,
                            PokemonId = 1,
                            Rating = 1,
                            ReviewerId = 3,
                            Text = "Pickchu, pickachu, pikachu",
                            Title = "Pikachu"
                        },
                        new
                        {
                            Id = 4,
                            PokemonId = 2,
                            Rating = 5,
                            ReviewerId = 1,
                            Text = "squirtle is the best pokemon, because it is electric",
                            Title = "Squirtle"
                        },
                        new
                        {
                            Id = 5,
                            PokemonId = 2,
                            Rating = 5,
                            ReviewerId = 2,
                            Text = "Squirtle is the best a killing rocks",
                            Title = "Squirtle"
                        },
                        new
                        {
                            Id = 6,
                            PokemonId = 2,
                            Rating = 1,
                            ReviewerId = 3,
                            Text = "squirtle, squirtle, squirtle",
                            Title = "Squirtle"
                        },
                        new
                        {
                            Id = 7,
                            PokemonId = 3,
                            Rating = 5,
                            ReviewerId = 1,
                            Text = "Venasuar is the best pokemon, because it is electric",
                            Title = "Veasaur"
                        },
                        new
                        {
                            Id = 8,
                            PokemonId = 3,
                            Rating = 5,
                            ReviewerId = 2,
                            Text = "Venasuar is the best a killing rocks",
                            Title = "Veasaur"
                        },
                        new
                        {
                            Id = 9,
                            PokemonId = 3,
                            Rating = 1,
                            ReviewerId = 3,
                            Text = "Venasuar, Venasuar, Venasuar",
                            Title = "Veasaur"
                        });
                });

            modelBuilder.Entity("PokReview.Models.Reviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reviewers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Teddy",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Taylor",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jessica",
                            LastName = "McGregor"
                        });
                });

            modelBuilder.Entity("PokReview.Models.Owner", b =>
                {
                    b.HasOne("PokReview.Models.Country", "Country")
                        .WithMany("Owners")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PokReview.Models.PokemonCategory", b =>
                {
                    b.HasOne("PokReview.Models.Category", "Category")
                        .WithMany("PokemonCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokReview.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonCategories")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokReview.Models.PokemonOwner", b =>
                {
                    b.HasOne("PokReview.Models.Owner", "Owner")
                        .WithMany("PokemonOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokReview.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonOwners")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokReview.Models.Review", b =>
                {
                    b.HasOne("PokReview.Models.Pokemon", "Pokemon")
                        .WithMany("Reviews")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokReview.Models.Reviewer", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PokReview.Models.Category", b =>
                {
                    b.Navigation("PokemonCategories");
                });

            modelBuilder.Entity("PokReview.Models.Country", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("PokReview.Models.Owner", b =>
                {
                    b.Navigation("PokemonOwners");
                });

            modelBuilder.Entity("PokReview.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonCategories");

                    b.Navigation("PokemonOwners");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PokReview.Models.Reviewer", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
